### ISSUE TITLE
ThreadLocal Memory Leak: com.codahale.metrics.ThreadLocalRandom

### ISSUE THREAD

**Issue by jnehlmeier** [dropwizard/metrics#742]
Using Metrics 3.1.0 there is a static `ThreadLocal` in `com.codahale.metrics.ThreadLocalRandom` that is never cleaned up.
This causes app server threads to hold references to this `ThreadLocalRandom` and thus the app ClassLoader can never be garbage collected.

It is a common misunderstanding that the `ThreadLocalMap.Entry` class prevents such leaks as it extends `WeakReference`. However the `Entry` class only weakly references the key (the `ThreadLocal` instance) and not the value (the `com.codahale.metrics.ThreadLocalRandom` instance).
So when a web app gets undeployed then the weakly referenced `ThreadLocal` instance might get cleaned up but the corresponding `ThreadLocalMap.Entry` instance is still in the map and still holds a strong reference to its value. `ThreadLocalMap` has some code to detect these stale entries but this code only gets triggered when calling `ThreadLocal.set()` or `ThreadLocal.remove()` ... which does not happen here.

![leak](https://cloud.githubusercontent.com/assets/1703797/5900294/a4a0a4b4-a567-11e4-9e26-cf81770b05fc.png)

The above screenshot shows the GC root excluding `WeakReference` to further illustrate that the leak exists and is caused by the `ThreadLocal.ThreadLocalMap.Entry.value` field.

Either do not use `ThreadLocal` or provide a clean up mechanism that can be called in a `ServletContextListener`.

**Comment by joe-devries-sp** [comment]
Related: https://github.com/dropwizard/metrics/issues/272 https://github.com/dropwizard/metrics/issues/248

**Comment by ryantenney** [comment]
I'm open to adding a clean up mechanism and ServletContextListener, but ideally we'd make it completely transparent to the user.

**Comment by jnehlmeier** [comment]
I have also observed that this ThreadLocal classloader leak occurs on other persistent app server threads like Jetty's Scanner Thread. During deployment it probably touches every class once which initializes the static ThreadLocal field in ThreadLocalRandom. So without any request the deployed app can not be garbage collected anymore.

To fix all possible leaks metrics would need to:
- Make initialization of the ThreadLocal in ThreadLocalRandom lazy so that it won't be triggered during deployment / class loading.
- Either provide a servlet filter that can call a cleanup method to remove the ThreadLocalRandom from the current request thread or a ServletContextListener that does cleanup for all threads once the app is undeployed. However if more than one app is deployed at the same time then the ServletContextListener solution might clean threads that are currently handling requests for other apps. So I guess a servlet filter would be preferable.

Alternatively for Java7+ users it might be possible to provide a separate metrics-core library that uses java.util.concurrent.ThreadLocalRandom of Java7+. In that case the classloader leak would be gone as ThreadLocalRandom would be loaded by the system classloader. 
However you might still have a slightly memory leak because continuous deployment of apps would cause new ThreadLocal instances to be stored in a thread's ThreadLocalMap. But maybe these ThreadLocal instances get cleaned up over time by the code provided in ThreadLocalMap.

**Comment by DustinChaloupka** [comment]
Where does this issue currently stand?  Curious about if someone is working on it or not.

**Comment by adamdecaf** [comment]
Would a patch be accepted that copied over the updated improvements from some of the updated source?  http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/ThreadLocalRandom.java?view=markup

**Comment by DustinChaloupka** [comment]
So was doing some digging around to see if I could get something to work, but it looks like what the Java 7 of ThreadLocalRandom is using for its seeding (declared fields in class `Thread` namely `threadLocalRandomSeed` and `threadLocalRandomProbe`) are not a part of `Thread` in Java 6.  So unless someone else has other ideas on patching that over, I'm not sure we can. =\

**Comment by nani83** [comment]
Using dropwizard 3.1.0(core) with Jdk7 and jboss8. Observing threadlocal related memory issues....any fix to overcome this?

**Comment by nani83** [comment]
How to use Java7's ThreadLocalRandom to avoid Thread local related issues?

**Comment by jnehlmeier** [comment]
@nani83 checkout the 3.1 branch, delete ThreadLocalRandom from Metrics and fix imports so it uses the Java7 version.

**Comment by nani83** [comment]
Thanks. Since, it is manual, I thought there might be another way/version which I can use. Will check this. Another query, As you were mentioning in previous post, Do we need explicit cleanup of threadlocals in filters/listener to overcome this issue completely?

**Comment by philippe-tr** [comment]
What is the status of this issue? We're having the same problem I think. When we issue the command `catalina.sh stop` we get the following error messages in catalina.out.

    SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks The web application [/capdServices] created a ThreadLocal with key of type [com.codahale.metrics.Striped64.ThreadHashCode] (value [com.codahale.metrics.Striped64$ThreadHashCode@xyz]) and a value of type [com.codahale.metrics.Striped64.HashCode] (value [com.codahale.metrics.Striped64$HashCode@xyz]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks The web application [/capdServices] created a ThreadLocal with key of type [com.codahale.metrics.ThreadLocalRandom$1] (value [com.codahale.metrics.ThreadLocalRandom$1@xyz]) and a value of type [com.codahale.metrics.ThreadLocalRandom] (value [com.codahale.metrics.ThreadLocalRandom@xyz]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by adamdecaf** [comment]
Hey all, just wanted to say we've forked this repo and back ported the fix ([diff](https://github.com/dropwizard/metrics/compare/3.1-maintenance...Banno:3.1-maintenance)) (it wont work on java6) from @DustinChaloupka (#757) over [under banno/metrics](https://github.com/Banno/metrics).

**Comment by philippe-tr** [comment]
@adamdecaf , will you issue a pull request to @ryantenney ? Is there any plan for the code to come back into this repo?

**Comment by adamdecaf** [comment]
@philippe-tr The fix was already committed to [dropwizard/master](https://github.com/dropwizard/metrics/commit/3ad79c7ec66e1d925af69f41986d38fa19247098). So everyone is free to cherry-pick that off. The rest of the changes were just to get the versions correct when packaging the jar.

**Comment by philippe-tr** [comment]
Ok. Too bad it did not make it to a release packaged on maven central. I can make my own in-house release for now I suppose.

**Comment by adamdecaf** [comment]
@philippe-tr yea, I didn't want to deal with that, and we have an internal repository we use.

**Comment by horn-rimmed-glasses** [comment]
@philippe-tr Did this resolve your issue? I am experiencing the same *first* error message as you, even with the cherry-pick on top of 3.1.0.

    SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks The web application [/capdServices] created a ThreadLocal with key of type [com.codahale.metrics.Striped64.ThreadHashCode] (value [com.codahale.metrics.Striped64$ThreadHashCode@xyz]) and a value of type [com.codahale.metrics.Striped64.HashCode] (value [com.codahale.metrics.Striped64$HashCode@xyz]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Any idea of how to resolve?

**Comment by philippe-tr** [comment]
@horn-rimmed-glasses No I did not work through this yet.

**Comment by static-max** [comment]
Any news on this?

**Comment by adamdecaf** [comment]
We're still running our fork of this library. Has there been much development on this project?

**Comment by coolfeature** [comment]
+1

**Comment by vazzick** [comment]
Is this still leaking in 3.1.2?

**Comment by tadgh** [comment]
I still have this issue on latest.

**Comment by adamdecaf** [comment]
We're still on the fork I've mentioned previously on this.

**Comment by fjamal21** [comment]
any update on this? when can we expect a fix for this?

**Comment by gymaganis** [comment]
+1

**Comment by arteam** [comment]
Submitted #1052 to fix this for the 3.1 branch.

**Comment by arteam** [comment]
I guess it should be fixed by #1052

**Comment by fbarbat** [comment]
Just in case it is useful for somebody, this problem is still happening in 3.2.2 on Java 6. If I am correct, this is because #1052 fixes the problem for JDK7 and above. Another argument for convincing management to invest time in updating Java...

**Comment by arteam** [comment]
Yes. Unfortunately, it's not possible to patch the internal `ThreadLocalRandom`, because the JDK version uses the internal JDK8 API. I couldn't find a version with the fix in the CVS history of JSR-166 compatible with Java 6/Java 7.

**Comment by codesinthedark** [comment]
I had similar problem and I implemented a different ThreadLocal class that will enable class loaders to be GC-ed on redeploy. It is different than other similar attempts (like VicariousThreadLocal and other classes) because it is completely non-blocking (even for setting values, not only for getting).
